name: Deploy

on:
  schedule:
    # Run at 7am every day
    - cron:  '0 7 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH: ssh demo
      # switch version to "nutmeg" once the branches have been created
      VERSION: nightly
    steps:
      # Install
      # https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/demo.key
          chmod 600 ~/.ssh/demo.key
          cat >>~/.ssh/config <<END
          Host demo
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/demo.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEMO_SSH_USER }}
          SSH_KEY: ${{ secrets.DEMO_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEMO_SSH_HOST }}
      - name: Upgrade dependencies
        run: $SSH 'pip install --user --upgrade pyyaml'
      - name: Install tutor and plugins (from source)
        run: $SSH pip install --user --upgrade -e git+https://github.com/overhangio/tutor.git@$VERSION#egg=tutor
      # - name: Install plugins (from source)
      #   run: $SSH pip install --user --upgrade -e git+https://github.com/overhangio/tutor-mfe.git@$VERSION#egg=tutor-mfe
      # Configure
      # - name: Enable plugins
      #   run: $SSH '~/.local/bin/tutor plugins enable mfe'
      - name: Configure tutor settings
        run: $SSH '~/.local/bin/tutor config save --set LMS_HOST=nutmeg.demo.overhang.io --set CMS_HOST=studio.nutmeg.demo.overhang.io --set ENABLE_HTTPS=true --set PLATFORM_NAME="Open edx Nutmeg Demo"'
      # Build
      - name: Build images
        run: $SSH '~/.local/bin/tutor images build all'
      # Launch
      - name: Quickstart
        run: $SSH '~/.local/bin/tutor local quickstart --non-interactive'
      # Provision
      - name: Create super user
        run: $SSH '~/.local/bin/tutor local createuser --staff --superuser --password=admin admin admin@overhang.io'
      - name: Create student user
        run: $SSH '~/.local/bin/tutor local createuser --password=student student student@overhang.io'
      - name: Import demo course
        run: $SSH '~/.local/bin/tutor local importdemocourse'
